from sgr_deep_research.agent_settings import AgentDefinition

DEFAULT_AGENTS = [
    AgentDefinition(
        name="sgr_agent",
        display_name="SGR Research Agent",
        description="Deep research agent using SGR framework with planning and reasoning",
        base_class="SGRResearchAgent",
        tools=[
            "ClarificationTool",
            "GeneratePlanTool",
            "AdaptPlanTool",
            "FinalAnswerTool",
            "WebSearchTool",
            "ExtractPageContentTool",
            "CreateReportTool",
            "MCPReadWikiStructure",
            "MCPReadWikiContents",
            "MCPAskQuestion",
        ],
    ),
    AgentDefinition(
        name="tool_calling_agent",
        display_name="Tool Calling Agent",
        description="Research agent using native LLM function calling",
        base_class="ToolCallingResearchAgent",
        tools=[
            "ClarificationTool",
            "GeneratePlanTool",
            "AdaptPlanTool",
            "FinalAnswerTool",
            "WebSearchTool",
            "ExtractPageContentTool",
            "CreateReportTool",
            "MCPReadWikiStructure",
            "MCPReadWikiContents",
            "MCPAskQuestion",
        ],
    ),
    AgentDefinition(
        name="sgr_tool_calling_agent",
        display_name="SGR Tool Calling Agent",
        description="SGR agent with native function calling for tool selection",
        base_class="SGRToolCallingResearchAgent",
        tools=[
            "ClarificationTool",
            "GeneratePlanTool",
            "AdaptPlanTool",
            "FinalAnswerTool",
            "WebSearchTool",
            "ExtractPageContentTool",
            "CreateReportTool",
            "MCPReadWikiStructure",
            "MCPReadWikiContents",
            "MCPAskQuestion",
        ],
    ),
    AgentDefinition(
        name="sgr_auto_tool_calling_agent",
        display_name="SGR Auto Tool Calling Agent",
        description="SGR agent with automatic tool selection",
        base_class="SGRAutoToolCallingResearchAgent",
        tools=[
            "ClarificationTool",
            "GeneratePlanTool",
            "AdaptPlanTool",
            "FinalAnswerTool",
            "WebSearchTool",
            "ExtractPageContentTool",
            "CreateReportTool",
            "MCPReadWikiStructure",
            "MCPReadWikiContents",
            "MCPAskQuestion",
        ],
    ),
    AgentDefinition(
        name="sgr_so_tool_calling_agent",
        display_name="SGR Structured Output Agent",
        description="SGR agent using structured outputs for tool calling",
        base_class="SGRSOToolCallingResearchAgent",
        tools=[
            "ClarificationTool",
            "GeneratePlanTool",
            "AdaptPlanTool",
            "FinalAnswerTool",
            "WebSearchTool",
            "ExtractPageContentTool",
            "CreateReportTool",
            "MCPReadWikiStructure",
            "MCPReadWikiContents",
            "MCPAskQuestion",
        ],
    ),
]
